.github/workflows/build.yml, pom.xml
-Fixed bug where text wasn't centred
-Text now centered
=> Pie chart bug fix

.github/workflows/build.yml
=> FIX for sonar #46

src/main/java/com/example/budgettracker/BudgetCategoriesController.java
Rewrite logic to show correct user input value for budget on the budget categories scene.
=> Set user budget value #70

src/main/java/com/example/budgettracker/BudgetCategoriesController.java, src/main/resources/com/example/budgettracker/budget-categories.fxml
-Connected category to summary
=> Connected BudgetCategoriesController to the Overview summary #75

.github/workflows/build.yml, pom.xml
- Fixed the README hyperlinks for contributor guidelines and license. 
- Removed the version section
Closes issue #80
=> Fix: README hyperlinks

src/main/java/com/example/budgettracker/BudgetCategoriesController.java, src/main/resources/com/example/budgettracker/budget-categories.fxml
- Added the use of total budgeted text on budget page
=> feat -continued use of total budgeted text

src/main/java/com/example/budgettracker/controller/BudgetOverviewController.java, src/main/resources/com/example/budgettracker/budget-overview.fxml
- Added line chart showing savings forecast
- Popup showing value of pie slice and line chart point on hover
- If chose saving goal, any leftover budget is now set as extra savings in pie chart and line chart includes extra savings
closes #54
=> Forecasting feature

src/main/java/com/example/budgettracker/controller/BudgetOverviewController.java, src/main/java/com/example/budgettracker/profiles/ProfileRepository.java, src/main/java/data/player_data.json
Completed basic text export feature for data
Added necessary comments
Refactored necessary code
#55
=> feat - user can save their info to text file

src/main/java/com/example/budgettracker/controller/BudgetOverviewController.java
- Forecasting shows yearly properly
=> bug - fixed forecasting so it shows yearly properly

src/main/java/data/player_data.json, src/main/resources/com/example/budgettracker/budget-entry.fxml, src/main/resources/com/example/budgettracker/select-profile.fxml
- now looks more professional and in line with the rest of the app
Closes #98
=> feature: changed text input fields

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- Updated the bug report template to include device version details
- Also updated the feature request template to include more context
=> fix: Updated the issue report templates to include all important details

.github/workflows/build.yml, .github/workflows/sonarcloud.yml
- Modified the sonar build/config files, so that Sonar cloud can work with the workflow of fork/merge.
=> fix: Updated sonar config to make it work with our workflow

src/main/java/com/example/budgettracker/BudgetCategoriesController.java, src/main/java/com/example/budgettracker/controller/BudgetOverviewController.java, src/main/java/data/player_data.json
Changed the file type exporting to CSV
Instead of user data, it is now giving information about the possible amount of saving as a CSV
Closes #55
=> Feature exporting

src/main/java/com/example/budgettracker/controller/BudgetEntryController.java, src/main/java/com/example/budgettracker/controller/BudgetOverviewController.java, src/main/java/com/example/budgettracker/profiles/Profile.java, src/main/java/com/example/budgettracker/profiles/ProfileRepository.java, src/main/java/data/player_data.json
Made some changes as advised by @dhruvkanth. Made it format like the rest of the files.
Made some improvements to the CSV function by using income for readability.
#55
=> exporting feature

CONTRIBUTING.md, README.md
- Updated readme with new team details
- Added more contribution details to the documentation, which would help new developers starting with the development
=> chore: Updated documentation to include new details

src/main/java/com/example/budgettracker/controller/BudgetCategoriesController.java, src/main/java/com/example/budgettracker/controller/CategoryItemController.java, src/main/resources/com/example/budgettracker/budget-categories.fxml, src/main/resources/com/example/budgettracker/categoryItem.fxml
- fixed the project structure and made it consistent by putting the files in the correct packages
=> fix: put the controller classes in the respective packages

src/main/java/data/player_data.json
- fixed the add user button to show the correct text instead of '?'
=> fix: fixed the add user button to show the correct text

src/main/java/com/example/budgettracker/BudgetCategoriesController.java, src/main/resources/com/example/budgettracker/budget-categories.fxml
- fixed the categories expense button not working
=> fix: fixed the categorise expense button not working

.github/ISSUE_TEMPLATE/ASIE.md
- Added an issue report template for App Store Inspired Elicitation (ASIE) issues
=> chore: added an issue report template for ASIE

src/main/resources/com/example/budgettracker/edit-profile.fxml
Designed and implemented a new scene to allow users to edit the profile picture as well as their username.
closes #111
=> feat:Created new scene for editing user profile

src/main/java/com/example/budgettracker/BudgetCategoriesController.java, src/main/java/com/example/budgettracker/controller/BudgetEntryController.java, src/main/java/com/example/budgettracker/controller/BudgetOverviewController.java, src/main/java/com/example/budgettracker/controller/CategoryItemController.java, src/main/java/com/example/budgettracker/controller/ChartController.java, src/main/java/com/example/budgettracker/profiles/Profile.java
All monetary values shown now have the correct currency symbol.
Closes #128
=> fix - all monetary values now have the correct currency symbol
